version: '3'

services:
  asterisk:
    build: ./asterisk
    ports:
      - 8890-8899:8888/tcp
      - 6060-6069:5060/udp
    links:
      - consul
      - rabbitmq
    expose:
      - 8888/tcp
      - 5060/udp
    volumes:
      - ./asterisk/dev:/usr/src/dev
  api-gateway:
    build: ./api-gateway
    ports:
      - 8088:80/tcp
    links:
      - consul
    expose:
      - 80/tcp
  consul:
    image: consul
    ports:
      - 8500:8500/tcp
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672/tcp
      - 15672:15672/tcp
    expose:
      - 5672/tcp
      - 15672/tcp
  kamailio:
    build: ./kamailio
    links:
      - consul
      - asterisk
    ports:
      - 5060:5060/udp
    expose:
      - 5060/udp
  astts:
    build: 
      context: ./apps
      dockerfile: ./astts/Dockerfile
    links:
      - consul
      - api-gateway
      - rabbitmq
      - asterisk
    expose:
      - 8001/tcp
    ports:
      - 8001:8001/tcp
    environment:
      - API_ENDPOINT=http://api-gateway
      - AMQP_HOST=rabbitmq
      - CONSUL_HOST=consul
      - APP_HOST=astts
      - APP_PORT=8001
  conf:
    build: 
      context: ./apps
      dockerfile: ./conf/Dockerfile
    links:
      - consul
      - api-gateway
      - rabbitmq
      - asterisk
    expose:
      - 8002/tcp
    ports:
      - 8002:8002/tcp
    environment:
      - API_ENDPOINT=http://api-gateway
      - AMQP_HOST=rabbitmq
      - CONSUL_HOST=consul
      - APP_HOST=conf
      - APP_PORT=8002
  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=wazo
    expose:
       - 5432/tcp
  wazo-auth:
    build: ./wazo-auth
    ports:
      - 9497:9497/tcp
    volumes:
      - ./wazo-auth/etc:/etc/wazo-auth
    links:
      - postgresql
      - consul
      - asterisk
    environment:
      - XIVO_UUID=123
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=wazo
      - USERNAME=admin
      - PASSWORD=secret
      - UUID=acea422c-84cf-4dd5-a244-6108d3a7e6e4
  wazo-websocketd:
    build: ./wazo-websocketd
    ports:
      - 9502:9502/tcp
    volumes:
      - ./wazo-websocketd/etc:/etc/wazo-websocketd
    links:
      - wazo-auth
      - rabbitmq

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
